# Generated by Django 4.0.2 on 2022-05-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superuser', models.CharField(max_length=100)),
                ('space', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('check_user', models.BooleanField(default=False)),
            ],
        ),
    ]
