# Generated by Django 4.0.2 on 2022-05-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
